# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4a7bb893c07130fa3e2f078206974a901f9ce5bccf1227872aed61628bcd0d8752388d2a44725d821790c3d0a088306657fe2aea4c3ccf8bb19b475175ed851

test:
  secret_key_base: 74f2379077683efb6511573513a50440128cef69eaf82fbca7b01d85a65697abcacb183b4f1a51d43b251ef906f5a5f1f8378bdbecc6b44052c8504a60792738

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
